trigger:
- main
 
pool:
  vmImage: windows-latest
 
stages:
- stage: Terraform_Init_and_Plan
  displayName: "Terraform Init and Plan"
  jobs:
 
  - job: Terraform_Init
    displayName: "Terraform Init"
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTask@5
      inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            commandOptions: '-backend=false'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'Apex-svc'
        
 
  - job: Terraform_Plan
    displayName: "Terraform Plan"
    dependsOn: Terraform_Init
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        environmentServiceNameAzureRM: 'Apex-svc'
 
  - job: Terraform_Apply
    displayName: "Terraform Apply"
    dependsOn: Terraform_Plan
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'Apex-svc'